apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-bluegreen-demo
  namespace: argocd
spec:
  project: default

  # Git 저장소 설정
  source:
    repoURL: https://github.com/YOUR_USERNAME/argo-rollouts-demo.git
    targetRevision: main
    path: argocd-bluegreen-demo/manifests

  # 배포 대상 클러스터
  destination:
    server: https://kubernetes.default.svc
    namespace: rollouts-demo

  # 동기화 정책
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
